### ISSUE TITLE
We are twtxt bots

### ISSUE THREAD

**Issue by kseistrup** [mdom/we-are-twtxt#3]
How about a `we-are-twtxt-bots.txt` with a list of those ‘accounts’ that are completely automated (`8ball`, et al.), whether iteractive or not?

**Comment by mdom** [comment]
Great idea, definitely! Do you want to the list? Maybe we should comments for the bots, to explain what they do and update the import script to

```
< list.txt sed 's/\s*#.*//' | xargs -n2 twtxt follow
```

**Comment by kseistrup** [comment]
It's a very good idea with the comments!
