### ISSUE TITLE
Feeds (Bots too)

### ISSUE THREAD

**Issue by prologic** [mdom/we-are-twtxt#48]
Hi Team (_whoever you are_) 🗡️ 

So I built this thing recently I called [rss2twtxt](https://github.com/prologic/rss2twtxt) and now host a public free (_I am __NOT__ responsible for its use, nor provide any warranties orguaranteess of the quality of the service_)  at https://feeds.twtxt.net/

Where should we put the ever growing list of feeds that are starting to become available? I put about a dozen or there myself as I'm migrating away from traditional RSS/Atom readers and away from [CommaFeed](https://www.commafeed.com) to the use of twtxt itself; but is now starting to get a bit of traction/use from others in the what is otherwise (_currently_) a very small community of twtxt users.

Thoughts?

**Comment by kseistrup** [comment]
What if rss2twtxt had a feeds list in the same format as the `we-are-twtxt.txt`? I.e., a file with one or more lines, each line having a feed name and a URL, separated by a blank. Then interested parties could either download the file and add the feeds they want want, or they could add the whole shebang with e.g.

```sh
$ curl -s https://feeds.twtxt.net/we-are-feeds.txt | xargs -n2 twtxt follow
```

**Comment by prologic** [comment]
Works for me :) I'll add this as a feature in a day or two and make a new deployment!

**Comment by kseistrup** [comment]
Once yoiu're ready, please let us know, then we can announce the feed list on the frontpage of this repo.

**Comment by prologic** [comment]
Done!

This is now live at https://feeds.twtxt.net/we-are-feeds.txt

As a special case there is also content negotiation on the `/feeds` endpoint:

```#!sh
$ curl -q -s -o - -H 'Accept: text/plain' https://feeds.twtxt.net/feeds
Kulpin.net Kulpin.net/twtxt.txt
Schwartzreport Schwartzreport/twtxt.txt
cncf cncf/twtxt.txt
contrapoint contrapoint/twtxt.txt
docker_blog docker_blog/twtxt.txt
github_blog github_blog/twtxt.txt
golang_news golang_news/twtxt.txt
hacker_news hacker_news/twtxt.txt
hugo.soucy.cc hugo.soucy.cc/twtxt.txt
latest_linux_kernel_versions latest_linux_kernel_versions/twtxt.txt
linux_gizmos linux_gizmos/twtxt.txt
lobste.rs lobste.rs/twtxt.txt
luke smith's blog luke smith's blog/twtxt.txt
mc mc/twtxt.txt
newest_python_peps newest_python_peps/twtxt.txt
slashdot slashdot/twtxt.txt
tg-z' stars tg-z' stars/twtxt.txt
unexplained_mysteries unexplained_mysteries/twtxt.txt
xkcd xkcd/twtxt.txt
```

Enjoy! :)

**Comment by kseistrup** [comment]
Thanks @prologic!
