### ISSUE TITLE
CI for validating twtxt feeds

### ISSUE THREAD

**Issue by prologic** [mdom/we-are-twtxt#51]
Hi (again) 👋

I _think_ we should implement a Github Workflow to periodically validate feeds here and on PRs.

For example [bucket's feed](https://buckket.org/twtxt.txt) now returns a `403 Forbidden` 😢 and he created this thing originally!

What do you think?

**Comment by kseistrup** [comment]
I think it's a good idea to check for availability of the feeds mentioned in the lists here, but I am unsure how to do it and what critria to use. E.g., Keybase's webserver for `keybase.pub` is notoriously unstable and any twtxt files hosted on Keybase are likely to get flagged for being unavailable unless the criteria are relaxed.

And unless the flagging and possibly temporary removal is handled automatically, I can be worried that it will be quite a burden to make sure that all feeds are always available. In a way I'd rather that people opened an issue saying “Hey, this feed has been unavailable for N days, could you guys take a look at it?”

Ideally, the lists were handled in a decentralised fashion, though I don't have any idea how we would do that.

It seems ironic that @buckket's feed is unavailable — with a `403 Forbidden`, even.

**Comment by prologic** [comment]
So I'm willing to help write some automation to help you out here to keep the lists you maintain in this repo up-to-dated and valid. FYI I actually have built [twtxt.net](https://twtxt.net) to pull in these lists you graciously maintain (_as a default source list_).

I _think_ we should probably just check for things like:

- NXDOMAIN
- 404 Not Found
- 403 Forbidden

These are indicators the URI is no longer valid.

We can also do things with:

- 301 and 302

Anything else like timeouts or 502 or 503 can be just logged, but they may still work. What do you think?

Re @bucket's feed, yes I find that a bit Ironic too since he did originally come up with this idea :) Oh well! I guess I"m the new "bucket"  😂

**Comment by kseistrup** [comment]
Just a short notice so I won't forget (leaving in a few minutes):

* Keybase's server often reports `404 Not found` when in fact it's just a software glitch.
* We should probably also check for `410 Gone`, even if it's uncommon.

**Comment by kseistrup** [comment]
PS: Perhaps @mdom kan add you to this repo?

**Comment by mdom** [comment]
Sorry, for the delay. I was on holiday with my family. I just invited James to the repository. I'm not really sure if we really need a CI. After all, we all are probably fetching every twtxtfeed there is every day and notice right away when someones is down. But i'm also not against it, so have fun building it, @prologic

**Comment by mdom** [comment]
This repository became kinda weird for me, it's under my name, but mainly it's Klaus doing all the work... Thanks, @kseistrup :)

**Comment by kseistrup** [comment]
Perhaps we should have a twtxt organization with a we-are-twtxt repo?

**Comment by buckket** [comment]
@kseistrup A few years back we already created @twtxt and it has been a long-standing plan of mine to gather all twtxt related resources there and allow for multiple contributors, as I haven’t been able to keep up with all the development and my personal twtxt repo is not the perfect fit for all those extra bits of information. So maybe now is a good time to finally set that plan in motion!

**Comment by prologic** [comment]
Oh hello 👋 @buckket Nice to finally meet you!

I _know_ you originally came up with the whole [twtxt](https://twtxt.readthedocs.org) thing in the first place, but how would you feel about my taking over the Github Org? As you know I've sorta / more-or-less kickstarted the twtxt community into gear since launching [twtxt.net](https://twtxt.net) ~2 weeks ago. Some interesting stats so far on a $0 budget and BS/crappy marketing; ~40k hits/day, ~3-6 new users/day (_dozen or so active so far_), ~100-150 Twts/day and growing.

**Comment by mdom** [comment]
@prologic Can i close this thread or do you need this issue as reminder?

**Comment by prologic** [comment]
No we can close it. I will get around to this soon and just put PRs up.
